export const contactForm = {
	id: 'discover',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Company',
	headline: 'Our Story',
	description: 'Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
	buttonLabel: "We're Hiring! Click Here To Apply",
	imgStart: false,
	img: require('../../images/company-logo.png').default,
	alt: 'Planet',
	dark: false,
	primary: false,
	darkText: true,
}