export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Projects',
    headline: 'Recent Work',
    description: 'Our rich portfolio of previous work showcases our commitment to excellence, community empowerment, and sustainable practices. We have collaborated with a diverse range of clients, including local governments, private developers, and First Nations organizations, to deliver top-notch contracting solutions tailored to their unique needs. Our projects span various sectors, such as infrastructure, commercial development, and environmental stewardship, reflecting our versatile expertise and dedication to creating lasting, positive impacts.',
    buttonLabel: 'Get In Touch',
    imgStart: false,
    img: require('../../images/ironlinkedinthumb.png').default,
    alt: 'Rocket',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Company',
    headline: 'Real Estate Iron Story',
    description: 'All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable.',
    buttonLabel: "We're Hiring! Click Here To Apply",
    imgStart: true,
    img: require('../../images/company-logo.png').default,
    alt: 'Planet',
    dark: false,
    primary: false,
    darkText: true,
};
